all:
  vars:
    ansible_ssh_private_key_file: /home/ansible/.ssh/AnsibleKey

  children:
    localhost:
      hosts:
        localhost:
          ansible_connection: local

    minikube:
      hosts:
        192.168.217.136:
          ansible_port: 50111
          ansible_user: ansible